# Written by pkgcheck.py from the vercel/ai profile and its install list
FROM node@sha256:c3de60bf2f9dd0ac6370e6117950ff62d6e339527e7472301c9c78a017978392
RUN apt-get update && apt-get install -y --no-install-recommends git ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /work
RUN git init -q && git remote add origin https://github.com/vercel/ai.git \
 && git fetch -q --depth 1 origin e7f55a481fe2c39bd2540162ee8b45bd8de3354b && git checkout -q FETCH_HEAD \
 && printf '.corepack/\n.pnpm-store/\n.bin/\n.da-logs/\n' > .git/info/exclude
RUN export COREPACK_HOME=/work/.corepack COREPACK_ENABLE_DOWNLOAD_PROMPT=0 CI=1 NO_COLOR=1 PATH=/work/.bin:$PATH pnpm_config_verify_deps_before_run=error && mkdir -p /work/.bin && corepack enable --install-directory /work/.bin pnpm && pnpm install --frozen-lockfile --store-dir /work/.pnpm-store --filter 'ai...' --filter '@ai-sdk/gateway...' --filter '@ai-sdk/openai-compatible...' --filter '@ai-sdk/openai...' --filter '@ai-sdk/groq...' --filter '@ai-sdk/deepseek...' --filter '@ai-sdk/alibaba...' --filter '@ai-sdk/mistral...' --filter '@ai-sdk/moonshotai...' --filter '@ai-sdk/xai...' --filter '@ai-sdk/baseten...' --filter '@ai-sdk/cerebras...' --filter '@ai-sdk/deepinfra...' --filter '@ai-sdk/fireworks...' --filter '@ai-sdk/gmicloud...' --filter '@ai-sdk/google-vertex...' --filter '@ai-sdk/huggingface...' --filter '@ai-sdk/togetherai...' --filter '@ai-sdk/zai...' --filter '@ai-sdk/workflow...'
RUN export COREPACK_HOME=/work/.corepack COREPACK_ENABLE_DOWNLOAD_PROMPT=0 CI=1 NO_COLOR=1 PATH=/work/.bin:$PATH pnpm_config_verify_deps_before_run=error && mkdir -p /work/.bin && corepack enable --install-directory /work/.bin pnpm && pnpm --filter 'ai...' --filter '@ai-sdk/gateway...' --filter '@ai-sdk/openai-compatible...' --filter '@ai-sdk/openai...' --filter '@ai-sdk/groq...' --filter '@ai-sdk/deepseek...' --filter '@ai-sdk/alibaba...' --filter '@ai-sdk/mistral...' --filter '@ai-sdk/moonshotai...' --filter '@ai-sdk/xai...' --filter '@ai-sdk/baseten...' --filter '@ai-sdk/cerebras...' --filter '@ai-sdk/deepinfra...' --filter '@ai-sdk/fireworks...' --filter '@ai-sdk/gmicloud...' --filter '@ai-sdk/google-vertex...' --filter '@ai-sdk/huggingface...' --filter '@ai-sdk/togetherai...' --filter '@ai-sdk/zai...' --filter '@ai-sdk/workflow...' build
RUN env | cut -d= -f1 | sort > /etc/da-env-baseline
